# Generated by Django 5.0.4 on 2024-05-07 09:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(verbose_name=datetime.date(2024, 5, 7)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(verbose_name=datetime.date(2024, 5, 7)),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order_article',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.order'),
        ),
    ]
