# Generated by Django 5.0.4 on 2024-05-09 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(verbose_name=datetime.date(2024, 5, 9)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(verbose_name=datetime.date(2024, 5, 9)),
        ),
    ]
